#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngAAFinal2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBongAACusco2")]
	public partial class clqOngDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAuspiciador(Auspiciador instance);
    partial void UpdateAuspiciador(Auspiciador instance);
    partial void DeleteAuspiciador(Auspiciador instance);
    partial void InsertLibro(Libro instance);
    partial void UpdateLibro(Libro instance);
    partial void DeleteLibro(Libro instance);
    partial void InsertLibro_TSesion(Libro_TSesion instance);
    partial void UpdateLibro_TSesion(Libro_TSesion instance);
    partial void DeleteLibro_TSesion(Libro_TSesion instance);
    partial void InsertMentor(Mentor instance);
    partial void UpdateMentor(Mentor instance);
    partial void DeleteMentor(Mentor instance);
    partial void InsertResiliente(Resiliente instance);
    partial void UpdateResiliente(Resiliente instance);
    partial void DeleteResiliente(Resiliente instance);
    partial void InsertResiliente_TSesion(Resiliente_TSesion instance);
    partial void UpdateResiliente_TSesion(Resiliente_TSesion instance);
    partial void DeleteResiliente_TSesion(Resiliente_TSesion instance);
    partial void InsertSeguimiento(Seguimiento instance);
    partial void UpdateSeguimiento(Seguimiento instance);
    partial void DeleteSeguimiento(Seguimiento instance);
    partial void InsertSesion(Sesion instance);
    partial void UpdateSesion(Sesion instance);
    partial void DeleteSesion(Sesion instance);
    partial void InsertSesion_TAuspiciador(Sesion_TAuspiciador instance);
    partial void UpdateSesion_TAuspiciador(Sesion_TAuspiciador instance);
    partial void DeleteSesion_TAuspiciador(Sesion_TAuspiciador instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public clqOngDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBongAACusco2ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public clqOngDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clqOngDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clqOngDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clqOngDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Auspiciador> Auspiciador
		{
			get
			{
				return this.GetTable<Auspiciador>();
			}
		}
		
		public System.Data.Linq.Table<Libro> Libro
		{
			get
			{
				return this.GetTable<Libro>();
			}
		}
		
		public System.Data.Linq.Table<Libro_TSesion> Libro_TSesion
		{
			get
			{
				return this.GetTable<Libro_TSesion>();
			}
		}
		
		public System.Data.Linq.Table<Mentor> Mentor
		{
			get
			{
				return this.GetTable<Mentor>();
			}
		}
		
		public System.Data.Linq.Table<Resiliente> Resiliente
		{
			get
			{
				return this.GetTable<Resiliente>();
			}
		}
		
		public System.Data.Linq.Table<Resiliente_TSesion> Resiliente_TSesion
		{
			get
			{
				return this.GetTable<Resiliente_TSesion>();
			}
		}
		
		public System.Data.Linq.Table<Seguimiento> Seguimiento
		{
			get
			{
				return this.GetTable<Seguimiento>();
			}
		}
		
		public System.Data.Linq.Table<Sesion> Sesion
		{
			get
			{
				return this.GetTable<Sesion>();
			}
		}
		
		public System.Data.Linq.Table<Sesion_TAuspiciador> Sesion_TAuspiciador
		{
			get
			{
				return this.GetTable<Sesion_TAuspiciador>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAuspiciador")]
	public partial class Auspiciador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ruc;
		
		private string _Razon_Social;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Correo;
		
		private EntitySet<Sesion_TAuspiciador> _Sesion_TAuspiciador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrucChanging(string value);
    partial void OnrucChanged();
    partial void OnRazon_SocialChanging(string value);
    partial void OnRazon_SocialChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    #endregion
		
		public Auspiciador()
		{
			this._Sesion_TAuspiciador = new EntitySet<Sesion_TAuspiciador>(new Action<Sesion_TAuspiciador>(this.attach_Sesion_TAuspiciador), new Action<Sesion_TAuspiciador>(this.detach_Sesion_TAuspiciador));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ruc
		{
			get
			{
				return this._ruc;
			}
			set
			{
				if ((this._ruc != value))
				{
					this.OnrucChanging(value);
					this.SendPropertyChanging();
					this._ruc = value;
					this.SendPropertyChanged("ruc");
					this.OnrucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Razon_Social", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Razon_Social
		{
			get
			{
				return this._Razon_Social;
			}
			set
			{
				if ((this._Razon_Social != value))
				{
					this.OnRazon_SocialChanging(value);
					this.SendPropertyChanging();
					this._Razon_Social = value;
					this.SendPropertyChanged("Razon_Social");
					this.OnRazon_SocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAuspiciador_TSesion_TAuspiciador", Storage="_Sesion_TAuspiciador", ThisKey="ruc", OtherKey="ruc")]
		public EntitySet<Sesion_TAuspiciador> Sesion_TAuspiciador
		{
			get
			{
				return this._Sesion_TAuspiciador;
			}
			set
			{
				this._Sesion_TAuspiciador.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sesion_TAuspiciador(Sesion_TAuspiciador entity)
		{
			this.SendPropertyChanging();
			entity.Auspiciador = this;
		}
		
		private void detach_Sesion_TAuspiciador(Sesion_TAuspiciador entity)
		{
			this.SendPropertyChanging();
			entity.Auspiciador = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TLibro")]
	public partial class Libro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idLibro;
		
		private string _Nombre;
		
		private string _Autor;
		
		private int _NroCopias;
		
		private EntitySet<Libro_TSesion> _Libro_TSesion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLibroChanging(string value);
    partial void OnidLibroChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnNroCopiasChanging(int value);
    partial void OnNroCopiasChanged();
    #endregion
		
		public Libro()
		{
			this._Libro_TSesion = new EntitySet<Libro_TSesion>(new Action<Libro_TSesion>(this.attach_Libro_TSesion), new Action<Libro_TSesion>(this.detach_Libro_TSesion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLibro", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idLibro
		{
			get
			{
				return this._idLibro;
			}
			set
			{
				if ((this._idLibro != value))
				{
					this.OnidLibroChanging(value);
					this.SendPropertyChanging();
					this._idLibro = value;
					this.SendPropertyChanged("idLibro");
					this.OnidLibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autor", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Autor
		{
			get
			{
				return this._Autor;
			}
			set
			{
				if ((this._Autor != value))
				{
					this.OnAutorChanging(value);
					this.SendPropertyChanging();
					this._Autor = value;
					this.SendPropertyChanged("Autor");
					this.OnAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroCopias", DbType="Int NOT NULL")]
		public int NroCopias
		{
			get
			{
				return this._NroCopias;
			}
			set
			{
				if ((this._NroCopias != value))
				{
					this.OnNroCopiasChanging(value);
					this.SendPropertyChanging();
					this._NroCopias = value;
					this.SendPropertyChanged("NroCopias");
					this.OnNroCopiasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TLibro_TLibro_TSesion", Storage="_Libro_TSesion", ThisKey="idLibro", OtherKey="idLibro")]
		public EntitySet<Libro_TSesion> Libro_TSesion
		{
			get
			{
				return this._Libro_TSesion;
			}
			set
			{
				this._Libro_TSesion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libro_TSesion(Libro_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Libro = this;
		}
		
		private void detach_Libro_TSesion(Libro_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Libro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TLibro_TSesion")]
	public partial class Libro_TSesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idLibro;
		
		private string _idSesion;
		
		private EntityRef<Libro> _Libro;
		
		private EntityRef<Sesion> _Sesion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLibroChanging(string value);
    partial void OnidLibroChanged();
    partial void OnidSesionChanging(string value);
    partial void OnidSesionChanged();
    #endregion
		
		public Libro_TSesion()
		{
			this._Libro = default(EntityRef<Libro>);
			this._Sesion = default(EntityRef<Sesion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLibro", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idLibro
		{
			get
			{
				return this._idLibro;
			}
			set
			{
				if ((this._idLibro != value))
				{
					if (this._Libro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidLibroChanging(value);
					this.SendPropertyChanging();
					this._idLibro = value;
					this.SendPropertyChanged("idLibro");
					this.OnidLibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSesion", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSesion
		{
			get
			{
				return this._idSesion;
			}
			set
			{
				if ((this._idSesion != value))
				{
					if (this._Sesion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSesionChanging(value);
					this.SendPropertyChanging();
					this._idSesion = value;
					this.SendPropertyChanged("idSesion");
					this.OnidSesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TLibro_TLibro_TSesion", Storage="_Libro", ThisKey="idLibro", OtherKey="idLibro", IsForeignKey=true)]
		public Libro Libro
		{
			get
			{
				return this._Libro.Entity;
			}
			set
			{
				Libro previousValue = this._Libro.Entity;
				if (((previousValue != value) 
							|| (this._Libro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Libro.Entity = null;
						previousValue.Libro_TSesion.Remove(this);
					}
					this._Libro.Entity = value;
					if ((value != null))
					{
						value.Libro_TSesion.Add(this);
						this._idLibro = value.idLibro;
					}
					else
					{
						this._idLibro = default(string);
					}
					this.SendPropertyChanged("Libro");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSesion_TLibro_TSesion", Storage="_Sesion", ThisKey="idSesion", OtherKey="idSesion", IsForeignKey=true)]
		public Sesion Sesion
		{
			get
			{
				return this._Sesion.Entity;
			}
			set
			{
				Sesion previousValue = this._Sesion.Entity;
				if (((previousValue != value) 
							|| (this._Sesion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sesion.Entity = null;
						previousValue.Libro_TSesion.Remove(this);
					}
					this._Sesion.Entity = value;
					if ((value != null))
					{
						value.Libro_TSesion.Add(this);
						this._idSesion = value.idSesion;
					}
					else
					{
						this._idSesion = default(string);
					}
					this.SendPropertyChanged("Sesion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMentor")]
	public partial class Mentor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _dni;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Especialidad;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Estado;
		
		private string _idUsuario;
		
		private EntitySet<Sesion> _Sesion;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndniChanging(string value);
    partial void OndniChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnEspecialidadChanging(string value);
    partial void OnEspecialidadChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnidUsuarioChanging(string value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public Mentor()
		{
			this._Sesion = new EntitySet<Sesion>(new Action<Sesion>(this.attach_Sesion), new Action<Sesion>(this.detach_Sesion));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this.OnEspecialidadChanging(value);
					this.SendPropertyChanging();
					this._Especialidad = value;
					this.SendPropertyChanged("Especialidad");
					this.OnEspecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMentor_TSesion", Storage="_Sesion", ThisKey="dni", OtherKey="dni")]
		public EntitySet<Sesion> Sesion
		{
			get
			{
				return this._Sesion;
			}
			set
			{
				this._Sesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TMentor", Storage="_Usuario", ThisKey="idUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Mentor.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Mentor.Add(this);
						this._idUsuario = value.idUsuario;
					}
					else
					{
						this._idUsuario = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Mentor = this;
		}
		
		private void detach_Sesion(Sesion entity)
		{
			this.SendPropertyChanging();
			entity.Mentor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TResiliente")]
	public partial class Resiliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idResiliente;
		
		private string _Nombre;
		
		private string _ApellidoP;
		
		private string _ApellidoM;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Estado;
		
		private string _idSeguimiento;
		
		private string _idUsuario;
		
		private EntitySet<Resiliente_TSesion> _Resiliente_TSesion;
		
		private EntityRef<Seguimiento> _Seguimiento;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidResilienteChanging(string value);
    partial void OnidResilienteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoPChanging(string value);
    partial void OnApellidoPChanged();
    partial void OnApellidoMChanging(string value);
    partial void OnApellidoMChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnidSeguimientoChanging(string value);
    partial void OnidSeguimientoChanged();
    partial void OnidUsuarioChanging(string value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public Resiliente()
		{
			this._Resiliente_TSesion = new EntitySet<Resiliente_TSesion>(new Action<Resiliente_TSesion>(this.attach_Resiliente_TSesion), new Action<Resiliente_TSesion>(this.detach_Resiliente_TSesion));
			this._Seguimiento = default(EntityRef<Seguimiento>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idResiliente", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idResiliente
		{
			get
			{
				return this._idResiliente;
			}
			set
			{
				if ((this._idResiliente != value))
				{
					this.OnidResilienteChanging(value);
					this.SendPropertyChanging();
					this._idResiliente = value;
					this.SendPropertyChanged("idResiliente");
					this.OnidResilienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoP", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ApellidoP
		{
			get
			{
				return this._ApellidoP;
			}
			set
			{
				if ((this._ApellidoP != value))
				{
					this.OnApellidoPChanging(value);
					this.SendPropertyChanging();
					this._ApellidoP = value;
					this.SendPropertyChanged("ApellidoP");
					this.OnApellidoPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoM", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ApellidoM
		{
			get
			{
				return this._ApellidoM;
			}
			set
			{
				if ((this._ApellidoM != value))
				{
					this.OnApellidoMChanging(value);
					this.SendPropertyChanging();
					this._ApellidoM = value;
					this.SendPropertyChanged("ApellidoM");
					this.OnApellidoMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSeguimiento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string idSeguimiento
		{
			get
			{
				return this._idSeguimiento;
			}
			set
			{
				if ((this._idSeguimiento != value))
				{
					if (this._Seguimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSeguimientoChanging(value);
					this.SendPropertyChanging();
					this._idSeguimiento = value;
					this.SendPropertyChanged("idSeguimiento");
					this.OnidSeguimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TResiliente_TResiliente_TSesion", Storage="_Resiliente_TSesion", ThisKey="idResiliente", OtherKey="idResiliente")]
		public EntitySet<Resiliente_TSesion> Resiliente_TSesion
		{
			get
			{
				return this._Resiliente_TSesion;
			}
			set
			{
				this._Resiliente_TSesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSeguimiento_TResiliente", Storage="_Seguimiento", ThisKey="idSeguimiento", OtherKey="idSeguimiento", IsForeignKey=true)]
		public Seguimiento Seguimiento
		{
			get
			{
				return this._Seguimiento.Entity;
			}
			set
			{
				Seguimiento previousValue = this._Seguimiento.Entity;
				if (((previousValue != value) 
							|| (this._Seguimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seguimiento.Entity = null;
						previousValue.Resiliente.Remove(this);
					}
					this._Seguimiento.Entity = value;
					if ((value != null))
					{
						value.Resiliente.Add(this);
						this._idSeguimiento = value.idSeguimiento;
					}
					else
					{
						this._idSeguimiento = default(string);
					}
					this.SendPropertyChanged("Seguimiento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TResiliente", Storage="_Usuario", ThisKey="idUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Resiliente.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Resiliente.Add(this);
						this._idUsuario = value.idUsuario;
					}
					else
					{
						this._idUsuario = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resiliente_TSesion(Resiliente_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Resiliente = this;
		}
		
		private void detach_Resiliente_TSesion(Resiliente_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Resiliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TResiliente_TSesion")]
	public partial class Resiliente_TSesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idSesion;
		
		private string _idResiliente;
		
		private EntityRef<Resiliente> _Resiliente;
		
		private EntityRef<Sesion> _Sesion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSesionChanging(string value);
    partial void OnidSesionChanged();
    partial void OnidResilienteChanging(string value);
    partial void OnidResilienteChanged();
    #endregion
		
		public Resiliente_TSesion()
		{
			this._Resiliente = default(EntityRef<Resiliente>);
			this._Sesion = default(EntityRef<Sesion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSesion", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSesion
		{
			get
			{
				return this._idSesion;
			}
			set
			{
				if ((this._idSesion != value))
				{
					if (this._Sesion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSesionChanging(value);
					this.SendPropertyChanging();
					this._idSesion = value;
					this.SendPropertyChanged("idSesion");
					this.OnidSesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idResiliente", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idResiliente
		{
			get
			{
				return this._idResiliente;
			}
			set
			{
				if ((this._idResiliente != value))
				{
					if (this._Resiliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidResilienteChanging(value);
					this.SendPropertyChanging();
					this._idResiliente = value;
					this.SendPropertyChanged("idResiliente");
					this.OnidResilienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TResiliente_TResiliente_TSesion", Storage="_Resiliente", ThisKey="idResiliente", OtherKey="idResiliente", IsForeignKey=true)]
		public Resiliente Resiliente
		{
			get
			{
				return this._Resiliente.Entity;
			}
			set
			{
				Resiliente previousValue = this._Resiliente.Entity;
				if (((previousValue != value) 
							|| (this._Resiliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Resiliente.Entity = null;
						previousValue.Resiliente_TSesion.Remove(this);
					}
					this._Resiliente.Entity = value;
					if ((value != null))
					{
						value.Resiliente_TSesion.Add(this);
						this._idResiliente = value.idResiliente;
					}
					else
					{
						this._idResiliente = default(string);
					}
					this.SendPropertyChanged("Resiliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSesion_TResiliente_TSesion", Storage="_Sesion", ThisKey="idSesion", OtherKey="idSesion", IsForeignKey=true)]
		public Sesion Sesion
		{
			get
			{
				return this._Sesion.Entity;
			}
			set
			{
				Sesion previousValue = this._Sesion.Entity;
				if (((previousValue != value) 
							|| (this._Sesion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sesion.Entity = null;
						previousValue.Resiliente_TSesion.Remove(this);
					}
					this._Sesion.Entity = value;
					if ((value != null))
					{
						value.Resiliente_TSesion.Add(this);
						this._idSesion = value.idSesion;
					}
					else
					{
						this._idSesion = default(string);
					}
					this.SendPropertyChanged("Sesion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TSeguimiento")]
	public partial class Seguimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idSeguimiento;
		
		private int _Dias_Asistidos;
		
		private int _Dias_Falto;
		
		private int _Recaidas;
		
		private EntitySet<Resiliente> _Resiliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSeguimientoChanging(string value);
    partial void OnidSeguimientoChanged();
    partial void OnDias_AsistidosChanging(int value);
    partial void OnDias_AsistidosChanged();
    partial void OnDias_FaltoChanging(int value);
    partial void OnDias_FaltoChanged();
    partial void OnRecaidasChanging(int value);
    partial void OnRecaidasChanged();
    #endregion
		
		public Seguimiento()
		{
			this._Resiliente = new EntitySet<Resiliente>(new Action<Resiliente>(this.attach_Resiliente), new Action<Resiliente>(this.detach_Resiliente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSeguimiento", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSeguimiento
		{
			get
			{
				return this._idSeguimiento;
			}
			set
			{
				if ((this._idSeguimiento != value))
				{
					this.OnidSeguimientoChanging(value);
					this.SendPropertyChanging();
					this._idSeguimiento = value;
					this.SendPropertyChanged("idSeguimiento");
					this.OnidSeguimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias_Asistidos", DbType="Int NOT NULL")]
		public int Dias_Asistidos
		{
			get
			{
				return this._Dias_Asistidos;
			}
			set
			{
				if ((this._Dias_Asistidos != value))
				{
					this.OnDias_AsistidosChanging(value);
					this.SendPropertyChanging();
					this._Dias_Asistidos = value;
					this.SendPropertyChanged("Dias_Asistidos");
					this.OnDias_AsistidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dias_Falto", DbType="Int NOT NULL")]
		public int Dias_Falto
		{
			get
			{
				return this._Dias_Falto;
			}
			set
			{
				if ((this._Dias_Falto != value))
				{
					this.OnDias_FaltoChanging(value);
					this.SendPropertyChanging();
					this._Dias_Falto = value;
					this.SendPropertyChanged("Dias_Falto");
					this.OnDias_FaltoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recaidas", DbType="Int NOT NULL")]
		public int Recaidas
		{
			get
			{
				return this._Recaidas;
			}
			set
			{
				if ((this._Recaidas != value))
				{
					this.OnRecaidasChanging(value);
					this.SendPropertyChanging();
					this._Recaidas = value;
					this.SendPropertyChanged("Recaidas");
					this.OnRecaidasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSeguimiento_TResiliente", Storage="_Resiliente", ThisKey="idSeguimiento", OtherKey="idSeguimiento")]
		public EntitySet<Resiliente> Resiliente
		{
			get
			{
				return this._Resiliente;
			}
			set
			{
				this._Resiliente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resiliente(Resiliente entity)
		{
			this.SendPropertyChanging();
			entity.Seguimiento = this;
		}
		
		private void detach_Resiliente(Resiliente entity)
		{
			this.SendPropertyChanging();
			entity.Seguimiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TSesion")]
	public partial class Sesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idSesion;
		
		private string _Nombre;
		
		private System.DateTime _Fecha;
		
		private double _MontoSesion;
		
		private string _dni;
		
		private EntitySet<Libro_TSesion> _Libro_TSesion;
		
		private EntitySet<Resiliente_TSesion> _Resiliente_TSesion;
		
		private EntitySet<Sesion_TAuspiciador> _Sesion_TAuspiciador;
		
		private EntityRef<Mentor> _Mentor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSesionChanging(string value);
    partial void OnidSesionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnMontoSesionChanging(double value);
    partial void OnMontoSesionChanged();
    partial void OndniChanging(string value);
    partial void OndniChanged();
    #endregion
		
		public Sesion()
		{
			this._Libro_TSesion = new EntitySet<Libro_TSesion>(new Action<Libro_TSesion>(this.attach_Libro_TSesion), new Action<Libro_TSesion>(this.detach_Libro_TSesion));
			this._Resiliente_TSesion = new EntitySet<Resiliente_TSesion>(new Action<Resiliente_TSesion>(this.attach_Resiliente_TSesion), new Action<Resiliente_TSesion>(this.detach_Resiliente_TSesion));
			this._Sesion_TAuspiciador = new EntitySet<Sesion_TAuspiciador>(new Action<Sesion_TAuspiciador>(this.attach_Sesion_TAuspiciador), new Action<Sesion_TAuspiciador>(this.detach_Sesion_TAuspiciador));
			this._Mentor = default(EntityRef<Mentor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSesion", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSesion
		{
			get
			{
				return this._idSesion;
			}
			set
			{
				if ((this._idSesion != value))
				{
					this.OnidSesionChanging(value);
					this.SendPropertyChanging();
					this._idSesion = value;
					this.SendPropertyChanged("idSesion");
					this.OnidSesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoSesion", DbType="Float NOT NULL")]
		public double MontoSesion
		{
			get
			{
				return this._MontoSesion;
			}
			set
			{
				if ((this._MontoSesion != value))
				{
					this.OnMontoSesionChanging(value);
					this.SendPropertyChanging();
					this._MontoSesion = value;
					this.SendPropertyChanged("MontoSesion");
					this.OnMontoSesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string dni
		{
			get
			{
				return this._dni;
			}
			set
			{
				if ((this._dni != value))
				{
					if (this._Mentor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndniChanging(value);
					this.SendPropertyChanging();
					this._dni = value;
					this.SendPropertyChanged("dni");
					this.OndniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSesion_TLibro_TSesion", Storage="_Libro_TSesion", ThisKey="idSesion", OtherKey="idSesion")]
		public EntitySet<Libro_TSesion> Libro_TSesion
		{
			get
			{
				return this._Libro_TSesion;
			}
			set
			{
				this._Libro_TSesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSesion_TResiliente_TSesion", Storage="_Resiliente_TSesion", ThisKey="idSesion", OtherKey="idSesion")]
		public EntitySet<Resiliente_TSesion> Resiliente_TSesion
		{
			get
			{
				return this._Resiliente_TSesion;
			}
			set
			{
				this._Resiliente_TSesion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSesion_TSesion_TAuspiciador", Storage="_Sesion_TAuspiciador", ThisKey="idSesion", OtherKey="idSesion")]
		public EntitySet<Sesion_TAuspiciador> Sesion_TAuspiciador
		{
			get
			{
				return this._Sesion_TAuspiciador;
			}
			set
			{
				this._Sesion_TAuspiciador.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMentor_TSesion", Storage="_Mentor", ThisKey="dni", OtherKey="dni", IsForeignKey=true)]
		public Mentor Mentor
		{
			get
			{
				return this._Mentor.Entity;
			}
			set
			{
				Mentor previousValue = this._Mentor.Entity;
				if (((previousValue != value) 
							|| (this._Mentor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mentor.Entity = null;
						previousValue.Sesion.Remove(this);
					}
					this._Mentor.Entity = value;
					if ((value != null))
					{
						value.Sesion.Add(this);
						this._dni = value.dni;
					}
					else
					{
						this._dni = default(string);
					}
					this.SendPropertyChanged("Mentor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Libro_TSesion(Libro_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = this;
		}
		
		private void detach_Libro_TSesion(Libro_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = null;
		}
		
		private void attach_Resiliente_TSesion(Resiliente_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = this;
		}
		
		private void detach_Resiliente_TSesion(Resiliente_TSesion entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = null;
		}
		
		private void attach_Sesion_TAuspiciador(Sesion_TAuspiciador entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = this;
		}
		
		private void detach_Sesion_TAuspiciador(Sesion_TAuspiciador entity)
		{
			this.SendPropertyChanging();
			entity.Sesion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TSesion_TAuspiciador")]
	public partial class Sesion_TAuspiciador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ruc;
		
		private string _idSesion;
		
		private EntityRef<Sesion> _Sesion;
		
		private EntityRef<Auspiciador> _Auspiciador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrucChanging(string value);
    partial void OnrucChanged();
    partial void OnidSesionChanging(string value);
    partial void OnidSesionChanged();
    #endregion
		
		public Sesion_TAuspiciador()
		{
			this._Sesion = default(EntityRef<Sesion>);
			this._Auspiciador = default(EntityRef<Auspiciador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ruc
		{
			get
			{
				return this._ruc;
			}
			set
			{
				if ((this._ruc != value))
				{
					if (this._Auspiciador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrucChanging(value);
					this.SendPropertyChanging();
					this._ruc = value;
					this.SendPropertyChanged("ruc");
					this.OnrucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSesion", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSesion
		{
			get
			{
				return this._idSesion;
			}
			set
			{
				if ((this._idSesion != value))
				{
					if (this._Sesion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSesionChanging(value);
					this.SendPropertyChanging();
					this._idSesion = value;
					this.SendPropertyChanged("idSesion");
					this.OnidSesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSesion_TSesion_TAuspiciador", Storage="_Sesion", ThisKey="idSesion", OtherKey="idSesion", IsForeignKey=true)]
		public Sesion Sesion
		{
			get
			{
				return this._Sesion.Entity;
			}
			set
			{
				Sesion previousValue = this._Sesion.Entity;
				if (((previousValue != value) 
							|| (this._Sesion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sesion.Entity = null;
						previousValue.Sesion_TAuspiciador.Remove(this);
					}
					this._Sesion.Entity = value;
					if ((value != null))
					{
						value.Sesion_TAuspiciador.Add(this);
						this._idSesion = value.idSesion;
					}
					else
					{
						this._idSesion = default(string);
					}
					this.SendPropertyChanged("Sesion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAuspiciador_TSesion_TAuspiciador", Storage="_Auspiciador", ThisKey="ruc", OtherKey="ruc", IsForeignKey=true)]
		public Auspiciador Auspiciador
		{
			get
			{
				return this._Auspiciador.Entity;
			}
			set
			{
				Auspiciador previousValue = this._Auspiciador.Entity;
				if (((previousValue != value) 
							|| (this._Auspiciador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Auspiciador.Entity = null;
						previousValue.Sesion_TAuspiciador.Remove(this);
					}
					this._Auspiciador.Entity = value;
					if ((value != null))
					{
						value.Sesion_TAuspiciador.Add(this);
						this._ruc = value.ruc;
					}
					else
					{
						this._ruc = default(string);
					}
					this.SendPropertyChanged("Auspiciador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idUsuario;
		
		private string _ContrasenaUsuario;
		
		private string _Tipo_Usuario;
		
		private EntitySet<Mentor> _Mentor;
		
		private EntitySet<Resiliente> _Resiliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(string value);
    partial void OnidUsuarioChanged();
    partial void OnContrasenaUsuarioChanging(string value);
    partial void OnContrasenaUsuarioChanged();
    partial void OnTipo_UsuarioChanging(string value);
    partial void OnTipo_UsuarioChanged();
    #endregion
		
		public Usuario()
		{
			this._Mentor = new EntitySet<Mentor>(new Action<Mentor>(this.attach_Mentor), new Action<Mentor>(this.detach_Mentor));
			this._Resiliente = new EntitySet<Resiliente>(new Action<Resiliente>(this.attach_Resiliente), new Action<Resiliente>(this.detach_Resiliente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContrasenaUsuario", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string ContrasenaUsuario
		{
			get
			{
				return this._ContrasenaUsuario;
			}
			set
			{
				if ((this._ContrasenaUsuario != value))
				{
					this.OnContrasenaUsuarioChanging(value);
					this.SendPropertyChanging();
					this._ContrasenaUsuario = value;
					this.SendPropertyChanged("ContrasenaUsuario");
					this.OnContrasenaUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Tipo_Usuario
		{
			get
			{
				return this._Tipo_Usuario;
			}
			set
			{
				if ((this._Tipo_Usuario != value))
				{
					this.OnTipo_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Tipo_Usuario = value;
					this.SendPropertyChanged("Tipo_Usuario");
					this.OnTipo_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TMentor", Storage="_Mentor", ThisKey="idUsuario", OtherKey="idUsuario")]
		public EntitySet<Mentor> Mentor
		{
			get
			{
				return this._Mentor;
			}
			set
			{
				this._Mentor.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TResiliente", Storage="_Resiliente", ThisKey="idUsuario", OtherKey="idUsuario")]
		public EntitySet<Resiliente> Resiliente
		{
			get
			{
				return this._Resiliente;
			}
			set
			{
				this._Resiliente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mentor(Mentor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Mentor(Mentor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Resiliente(Resiliente entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Resiliente(Resiliente entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
}
#pragma warning restore 1591
